"""Type stubs for _spidev C extension module."""

from typing import Sequence
from typing_extensions import Buffer

__version__: str

class _SpiDev:
    def __init__(self, bus: int = -1, client: int = -1) -> None: ...
    def open(self, bus: int, device: int) -> None: ...
    def open_path(self, path: str) -> None: ...
    def close(self) -> None: ...
    def fileno(self) -> int: ...
    def readbytes(self, length: int) -> list[int]: ...
    def writebytes(self, values: Sequence[int]) -> None: ...
    def writebytes2(self, values: Sequence[int] | Buffer) -> None: ...
    def xfer(
        self,
        values: Sequence[int],
        speed_hz: int = 0,
        delay_usecs: int = 0,
        bits_per_word: int = 0,
    ) -> list[int]: ...
    def xfer2(
        self,
        values: Sequence[int],
        speed_hz: int = 0,
        delay_usecs: int = 0,
        bits_per_word: int = 0,
    ) -> list[int]: ...
    def xfer3(
        self,
        values: Sequence[int],
        speed_hz: int = 0,
        delay_usecs: int = 0,
        bits_per_word: int = 0,
    ) -> tuple[int, ...]: ...
    def __enter__(self) -> _SpiDev: ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> bool: ...
    @property
    def mode(self) -> int: ...
    @mode.setter
    def mode(self, value: int) -> None: ...
    @property
    def cshigh(self) -> bool: ...
    @cshigh.setter
    def cshigh(self, value: bool) -> None: ...
    @property
    def threewire(self) -> bool: ...
    @threewire.setter
    def threewire(self, value: bool) -> None: ...
    @property
    def lsbfirst(self) -> bool: ...
    @lsbfirst.setter
    def lsbfirst(self, value: bool) -> None: ...
    @property
    def loop(self) -> bool: ...
    @loop.setter
    def loop(self, value: bool) -> None: ...
    @property
    def no_cs(self) -> bool: ...
    @no_cs.setter
    def no_cs(self, value: bool) -> None: ...
    @property
    def bits_per_word(self) -> int: ...
    @bits_per_word.setter
    def bits_per_word(self, value: int) -> None: ...
    @property
    def max_speed_hz(self) -> int: ...
    @max_speed_hz.setter
    def max_speed_hz(self, value: int) -> None: ...
    @property
    def read0(self) -> bool: ...
    @read0.setter
    def read0(self, value: bool) -> None: ...
    @property
    def mosi_idle_low(self) -> bool: ...
    @mosi_idle_low.setter
    def mosi_idle_low(self, value: bool) -> None: ...
