name: Ruff Check

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ruff check
        uses: astral-sh/ruff-action@v3

      - name: Check formatting
        run: ruff format --check --diff
